server:
  port: 8084
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:hierarquia
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true

  devtools:
    remote:
      debug:
        local-port: 8010