server:
  port: 8084
# usuário e senha de conexão com o banco de dados
spring:
  datasource:
    username: root
    password: root
# url de conexão do banco de dados
    url: jdbc:mysql://localhost:3306/hierarquia # ?allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=true&createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
# apontamos para o JPA e Hibernate qual é o Dialeto do banco de dados
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
# deixamos o hibernate responsável por ler nossas entidades e criar as tabelas do nosso banco de dados automaticamente
    hibernate:
      ddl-auto: create
# configuração do Hibernate para reconhecer o nome de tabelas em caixa alta
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# configurações de log
    show-sql: true